[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add ='nn <silent><C-e> :NERDTreeToggle<CR>'

[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = 'nmap <F8> :TagbarToggle<CR>'

#[[plugins]]
#repo = 'powerline/powerline'
#rtp = 'powerline/bindings/vim/'

#lazy plugins
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = 'markdown'
hook_add = '''
let g:markdown_fenced_languages = ['html', 'python', 'bash=sh']
let g:markdown_minlines = 100
'''

[[plugins]]
repo = 'previm/previm'
on_ft = 'markdown'
hook_add = "let g:previm_open_cmd = 'firefox'"

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'JuliaEditorSupport/julia-vim'
hook_source = 'let g:default_julia_version = "1.2"'

[[plugins]]
repo = 'thinca/vim-quickrun'
