#[[plugins]]
#repo = 'autozimu/LanguageClient-neovim' 
#rev = 'next'
#build = 'bash install.sh'
#hook_source = '''source /home/sasuseso/.config/nvim/plugin_config/LanguageClient-neovim.vim'''
#[[plugins]]
#repo = 'prabirshrestha/async.vim'

#[[plugins]]
#repo = 'prabirshrestha/vim-lsp'
#hook_source = 'source /home/sasuseso/.config/nvim/plugin_config/vim-lsp.vim'
[[plugins]]
repo = 'JuliaEditorSupport/julia-vim'
hook_add = 'let g:default_julia_version = "1.3"'

[[plugins]]
repo = 'neoclide/coc.nvim'
marged = 0
rev = 'release'

[[plugins]]
repo = 'Shougo/dein.vim'
hook_post_update = ':UpdateRemotePlugins'

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_post_update = ':UpdateRemotePlugins'

[[plugins]]
repo = 'Shougo/neoinclude.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add ='nnoremap <silent><C-e> :NERDTreeToggle<CR>'

[[plugins]]
repo = 'jpalardy/vim-slime'
hook_add ='let g:slime_target = "tmux"'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
let s:denite_win_width_percent = 0.85
let s:denite_win_height_percent = 0.7

" Change denite default options
call denite#custom#option('default', {
    \ 'split': 'floating',
    \ 'winwidth': float2nr(&columns * s:denite_win_width_percent),
    \ 'wincol': float2nr((&columns - (&columns * s:denite_win_width_percent)) / 2),
    \ 'winheight': float2nr(&lines * s:denite_win_height_percent),
    \ 'winrow': float2nr((&lines - (&lines * s:denite_win_height_percent)) / 2),
    \ })
'''
hook_post_update = ':UpdateRemotePlugins'

[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = 'nmap <F8> :TagbarToggle<CR>'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
let g:deoplete#enable_at_startup = 1
let g:python3_host_prog='/usr/bin/python'
'''

[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = 'vim-airline'
hook_add = """
let g:airline_theme='iceberg'
let g:airline_powerline_fonts = 1
set laststatus=2
"""

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
let g:airline#extensions#tabline#enabled = 1
'''

[[plugins]]
repo = 'gorodinskiy/vim-coloresque'

[[plugins]]
repo = 'kdheepak/JuliaFormatter.vim'
hook_add = '''
" normal mode mapping
nnoremap <leader>jf :<C-u>call JuliaFormatter#Format(0)<CR>
" visual mode mapping
vnoremap <leader>jf :<C-u>call JuliaFormatter#Format(1)<CR>
'''

[[plugins]]
repo = 'thinca/vim-quickrun'

#[[plugins]]
#repo = 'w0rp/ale'

[[plugins]]
repo = 'tpope/vim-obsession'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'yuratomo/w3m.vim'

[[plugins]]
repo = 'twitvim/twitvim'

[[plugins]]
repo = 'fuenor/JpFormat.vim'
hook_add = 'set formatexpr=jpfmt#formatexpr()'

[[plugins]]
repo = 'voldikss/vim-floaterm'
hook_add = '''
let g:floaterm_keymap_toggle = '<F10>'
let g:floaterm_keymap_new = '<F3>'
let g:floaterm_position = 'center'
nmap <silent><F9> :FloatermNew ranger<CR>
nmap <silent><F6> :FloatermNew lazygit<CR>
'''

[[plugins]]
repo = 'liuchengxu/vim-clap'

#[[plugins]]
#repo = 'Shougo/neosnippet.vim'
#hook_source = '''
#let g:neosnippet#snippets_directory='/home/sasuseso/.config/nvim/snippets/'
#'''

#[[plugins]]
#repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'lambdalisue/gina.vim'

[[plugins]]
repo = 'mattn/vim-sonictemplate'

[[plugins]]
repo = 'skanehira/preview-markdown.vim'

[[plugins]]
repo = 'chr4/nginx.vim'

[[plugins]]
repo = "https://github.com/dag/vim-fish.git"

[[plugins]]
repo = "Yggdroot/indentLine"
hook_add = "let g:indentLine_char = '‚ñè'"

[[plugins]]
repo = "rhysd/vim-clang-format"
