[deps]
AbstractPlotting = "537997a7-5e4e-5d89-9595-2241ea00577e"
Atom = "c52e3926-4ff0-5f6e-af25-54175e0327b1"
CuArrays = "3a865a2d-5b23-5a0f-bc46-62713ec82fae"
Electron = "a1bb12fb-d4d1-54b4-b10a-ee7951ef7ad3"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
Gtk = "4c0ca9eb-093a-5379-98c5-f87ac0bbbf44"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Juno = "e5e0dc1b-0480-54bc-9374-aad01c23163d"
LLVM = "929cbde3-209d-540e-8aea-75f648917ca0"
LanguageServer = "2b0e0bc5-e4fd-59b4-8912-456d1b03d8d7"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
OhMyREPL = "5fb14364-9ced-5910-84b2-373655c76a03"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StaticLint = "b3cc710f-9c33-5bdb-a03d-a94903873e97"
SymbolServer = "cf896787-08d5-524d-9de7-132aaa0cb996"
URIParser = "30578b45-9adc-5946-b283-645ec420af67"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
